#ifndef ARINC653_SYSTEM_STATE_H_
#define ARINC653_SYSTEM_STATE_H_

namespace arinc653
{
	enum SYSTEM_STATE {
		MODULE_INITIALIZATION,
		MODULE_EXECUTION,
		PARTITON_INITIALIZATION,
		PARTITON_EXECUTION
	};

}//namespace arinc653

#endif //ARINC653_SYSTEM_STATE_H_